name: CI-CD

on:
  push:
    branches: ["main"]
    
jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Autenticação no Docker
        uses: docker/login-action@v2.1.0
        with:  
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          tags: |
            jfstrassburg/api-conversor-temperatura:${{github.run.number}}
