name: CI-CD

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    steps:
      - uses: actions/checkout@v2
        
      - name: Autenticação no Docker
        uses: docker/login-action@v2.1.0
        with:  
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
        
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            jfstrassburg/api-conversor-temperatura:${{github.run.number}}
            jfstrassburg/api-conversor-temperatura:Latest
